# Generated by Django 6.0.2 on 2026-03-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='color',
            field=models.CharField(default='#000000', max_length=20),
        ),
        migrations.AddField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='section',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
