# Generated by Django 5.1.15 on 2026-03-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_section_color_section_description_section_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nomi (RU)'),
        ),
        migrations.AddField(
            model_name='section',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nomi (RU)'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nomi (RU)'),
        ),
    ]
