# Generated by Django 5.1.15 on 2026-03-05 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_bushpeak_to_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='badge_ru',
            field=models.CharField(blank=True, max_length=50, verbose_name='Badge (RU)'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Rang (RU)'),
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.JSONField(blank=True, default=list, verbose_name='Ranglar (Variantlar)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Tavsif (RU)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nomi (RU)'),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.JSONField(blank=True, default=list, verbose_name="O'lchamlar"),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Brend (RU)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
