# Generated by Django 6.0.2 on 2026-03-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_badge_ru_product_color_ru_product_colors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='badge',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='badge_ru',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Badge (RU)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_ru',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Rang (RU)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_ru',
            field=models.TextField(blank=True, default='', verbose_name='Tavsif (RU)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ru',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nomi (RU)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_ru',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Brend (RU)'),
        ),
    ]
