# Generated by Django 5.1.15 on 2026-02-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('subtitle', models.TextField(blank=True, verbose_name='Qisqa tavsif')),
                ('cta_text', models.CharField(blank=True, max_length=64, verbose_name='Tugma matni')),
                ('cta_link', models.CharField(blank=True, max_length=255, verbose_name='Tugma havola')),
                ('image', models.ImageField(blank=True, upload_to='banners/', verbose_name='Rasm')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Bannerlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Savol')),
                ('answer', models.TextField(verbose_name='Javob')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQlar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('subtitle', models.TextField(verbose_name='Qisqa tavsif')),
                ('cta1_text', models.CharField(blank=True, max_length=64, verbose_name='CTA 1 matni')),
                ('cta1_link', models.CharField(blank=True, max_length=255, verbose_name='CTA 1 havola')),
                ('cta2_text', models.CharField(blank=True, max_length=64, verbose_name='CTA 2 matni')),
                ('cta2_link', models.CharField(blank=True, max_length=255, verbose_name='CTA 2 havola')),
                ('badge', models.CharField(blank=True, max_length=32, verbose_name='Badge')),
                ('image', models.ImageField(blank=True, upload_to='hero/', verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
            ],
            options={
                'verbose_name': 'Hero slayd',
                'verbose_name_plural': 'Hero slaydlar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nomi')),
                ('logo', models.ImageField(blank=True, upload_to='partners/', verbose_name='Logo')),
                ('website', models.URLField(blank=True, verbose_name='Veb-sayt')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
            ],
            options={
                'verbose_name': 'Hamkor',
                'verbose_name_plural': 'Hamkorlar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Ism')),
                ('role', models.CharField(blank=True, max_length=128, verbose_name='Lavozimi')),
                ('content', models.TextField(verbose_name='Sharh matni')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Reyting')),
                ('avatar', models.ImageField(blank=True, upload_to='testimonials/', verbose_name='Avatar')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
            ],
            options={
                'verbose_name': 'Sharh',
                'verbose_name_plural': 'Sharhlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
