# Generated by Django 6.0.2 on 2026-03-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('image', models.ImageField(blank=True, upload_to='instagram/', verbose_name='Rasm')),
                ('link', models.URLField(blank=True, help_text='Instagram post URL', verbose_name='Havola')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
            ],
            options={
                'verbose_name': 'Instagram post',
                'verbose_name_plural': 'Instagram postlar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='ArmyShop CH', max_length=128, verbose_name="Do'kon nomi")),
                ('tagline', models.CharField(default='Tashqi va Taktik', max_length=255, verbose_name='Tagline')),
                ('currency', models.CharField(default='CHF', max_length=10, verbose_name='Valyuta')),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=90, max_digits=10, verbose_name='Bepul yetkazish chegarasi')),
                ('phone', models.CharField(default='+41 79 176 16 17', max_length=30, verbose_name='Telefon')),
                ('email', models.EmailField(default='info@army-shop.ch', max_length=254, verbose_name='Email')),
                ('address', models.CharField(default='Shveytsariya', max_length=255, verbose_name='Manzil')),
                ('workday_hours', models.CharField(default='09:00 - 16:30', max_length=50, verbose_name='Ish kunlari soati')),
                ('saturday_hours', models.CharField(default='10:00 - 13:30', max_length=50, verbose_name='Shanba soati')),
                ('instagram_url', models.URLField(blank=True, default='https://www.instagram.com/swiss.armyshop/', verbose_name='Instagram')),
                ('facebook_url', models.URLField(blank=True, default='https://www.facebook.com/armyshop.ch/', verbose_name='Facebook')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO sarlavha')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO tavsif')),
                ('copyright_text', models.CharField(default='© 2026 Army Shop CH. Barcha huquqlar himoyalangan.', max_length=255, verbose_name='Copyright')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
    ]
