# Generated by Django 6.0.2 on 2026-03-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_instagrampost_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='animation_type',
            field=models.CharField(choices=[('fade-up', "Yuqoriga chiqib ko'rinish"), ('slide-left', "Xo'shdan kelib ko'rinish"), ('zoom-in', "Kattalashib ko'rinish"), ('blur-in', "Blur bilan ko'rinish")], default='fade-up', max_length=32, verbose_name='Animatsiya turi'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='cta1_bg_color',
            field=models.CharField(default='#ffffff', max_length=20, verbose_name='CTA 1 fon rangi'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='cta1_txt_color',
            field=models.CharField(default='#000000', max_length=20, verbose_name='CTA 1 matn rangi'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='cta2_bg_color',
            field=models.CharField(default='transparent', max_length=20, verbose_name='CTA 2 fon rangi'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='cta2_txt_color',
            field=models.CharField(default='#ffffff', max_length=20, verbose_name='CTA 2 matn rangi'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='overlay_color',
            field=models.CharField(default='#000000', max_length=20, verbose_name='Overlay rangi'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='overlay_opacity',
            field=models.FloatField(default=0.6, verbose_name='Overlay shaffofligi'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='text_align',
            field=models.CharField(choices=[('left', 'Chap'), ('center', 'Markaz'), ('right', "O'ng")], default='left', max_length=20, verbose_name='Matn tekislash'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='currency',
            field=models.CharField(default='UZS', max_length=10, verbose_name='Valyuta'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='free_shipping_threshold',
            field=models.DecimalField(decimal_places=2, default=500000, max_digits=12, verbose_name='Bepul yetkazish chegarasi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='shop_name',
            field=models.CharField(default='Con-Dor.Uz', max_length=128, verbose_name="Do'kon nomi"),
        ),
    ]
