# Generated by Django 6.0.2 on 2026-03-01 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_heroslide_animation_type_heroslide_cta1_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_bot_token',
            field=models.CharField(blank=True, max_length=255, verbose_name='Telegram Bot Token'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_channel_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram Kanal ID'),
        ),
    ]
