# Generated by Django 5.1.15 on 2026-03-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_sitesettings_telegram_bot_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='badge_ru',
            field=models.CharField(blank=True, max_length=32, verbose_name='Badge (RU)'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='cta1_text_ru',
            field=models.CharField(blank=True, max_length=64, verbose_name='CTA 1 matni (RU)'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='cta2_text_ru',
            field=models.CharField(blank=True, max_length=64, verbose_name='CTA 2 matni (RU)'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='subtitle_ru',
            field=models.TextField(blank=True, verbose_name='Qisqa tavsif (RU)'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sarlavha (RU)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='copyright_text_ru',
            field=models.CharField(default='© 2026 Army Shop CH. Все права защищены.', max_length=255, verbose_name='Copyright (RU)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline_ru',
            field=models.CharField(blank=True, default='Наружное и тактическое снаряжение', max_length=255, verbose_name='Tagline (RU)'),
        ),
    ]
