# Generated by Django 5.1.15 on 2026-03-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_content_seed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('name_ru', models.CharField(blank=True, max_length=255, verbose_name='Nomi (RU)')),
                ('address', models.CharField(max_length=255, verbose_name='Manzil')),
                ('address_ru', models.CharField(blank=True, max_length=255, verbose_name='Manzil (RU)')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('work_hours', models.CharField(blank=True, max_length=255, verbose_name='Ish vaqti')),
                ('work_hours_ru', models.CharField(blank=True, max_length=255, verbose_name='Ish vaqti (RU)')),
                ('location_url', models.TextField(blank=True, verbose_name='Xarita (Iframe src yoki URL)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiallar',
                'ordering': ['order', 'name'],
            },
        ),
    ]
