# Generated by Django 5.1.15 on 2026-03-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_url',
            field=models.URLField(blank=True, default='https://t.me/con_dor_uz', verbose_name='Telegram'),
        ),
    ]
