# Generated by Django 5.1.15 on 2026-02-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name="Obuna bo'lgan")),
            ],
            options={
                'verbose_name': 'Obunachi',
                'verbose_name_plural': 'Obunachlar',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
