# Generated by Django 6.0.2 on 2026-03-01 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('shop', '0003_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, help_text='Anonymous guest identifier', max_length=64, verbose_name='Sessiya kaliti')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Savat',
                'verbose_name_plural': 'Savatlar',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Soni')),
                ('size', models.CharField(blank=True, max_length=10, verbose_name="O'lcham")),
                ('color', models.CharField(blank=True, max_length=30, verbose_name='Rang')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan")),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.cart', verbose_name='Savat')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='shop.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Savat elementi',
                'verbose_name_plural': 'Savat elementlari',
                'constraints': [models.UniqueConstraint(fields=('cart', 'product', 'size', 'color'), name='unique_cart_item_variant')],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan")),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='shop.product', verbose_name='Mahsulot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Tanlangan',
                'verbose_name_plural': 'Tanlanganlar',
                'ordering': ['-added_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'product'), name='unique_wishlist_item')],
            },
        ),
    ]
